server:
  port: 8080

spring:
  thymeleaf:
    cache: false #关闭thymeleaf缓存
---
# 数据源配置
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8

# 动态配置
sqring:
  security:
    authentication:
      loginPage: /login/page # 响应认证(登录)页面URL
      loginProcessingUrl: /login/form # 登录表单提交处理Url
      usernameParameter: name # 登录表单用户名的属性名
      passwordParameter: pwd # 登录表单密码的属性名
      staticPaths:   # 静态资源 "/dist/**", "/modules/**", "/plugins/**"
      - /dist/**
      - /modules/**
      - /plugins/**
      loginType: REDIRECT # 认证之后 响应的类型：JSON/REDIRECT
      imageCodeUrl: /code/image # 获取图形验证码 url
      mobileCodeUrl: /code/mobile # 发送手机验证码 url
      mobilePage: /mobile/page # 前往手机登录页面地址
      tokenValiditySeconds: 604800 # 记住我有效时长，单位秒， 注意不要用乘法*，会被认为字符串
